package com.atm.management.service;

import com.atm.management.dto.response.StatementResponse;
import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;

@Service
public class StatementPdfService {

    private static final DateTimeFormatter DT =
            DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm");

    public byte[] render(StatementResponse statement, String accountNo) {
        StringBuilder rows = new StringBuilder();
        if (statement.transactions().isEmpty()) {
            rows.append("<tr><td colspan=\"4\" class=\"empty\">No transactions found</td></tr>");
        } else {
            for (StatementResponse.TransactionItem item : statement.transactions()) {
                boolean credit = "C".equals(item.direction())
                        || "Deposit".equals(item.type())
                        || "Transfer In".equals(item.type());
                String amountClass = credit ? "credit" : "debit";
                String prefix = credit ? "+" : "−";
                rows.append("<tr>")
                        .append("<td>").append(esc(item.date().format(DT))).append("</td>")
                        .append("<td>").append(esc(item.type())).append("</td>")
                        .append("<td class=\"").append(amountClass).append("\">")
                        .append(prefix).append(" Rs. ").append(item.amount().toPlainString())
                        .append("</td>")
                        .append("</tr>");
            }
        }

        String html = """
                <!DOCTYPE html>
                <html>
                <head>
                  <style>
                    @page { margin: 40px; }
                    body { font-family: Helvetica, Arial, sans-serif; color: #0f172a; font-size: 12px; }
                    h1 { font-size: 20px; color: #0f766e; margin: 0 0 4px 0; }
                    .sub { color: #64748b; margin: 0 0 18px 0; }
                    .meta { margin-bottom: 6px; }
                    table { width: 100%%; border-collapse: collapse; margin-top: 12px; }
                    th { text-align: left; background: #f1f5f9; border-bottom: 2px solid #0f766e; padding: 8px; }
                    td { padding: 8px; border-bottom: 1px solid #e2e8f0; }
                    .credit { color: #15803d; font-weight: bold; }
                    .debit { color: #dc2626; font-weight: bold; }
                    .empty { text-align: center; color: #64748b; padding: 24px; }
                    .footer { margin-top: 24px; color: #64748b; font-size: 10px; }
                  </style>
                </head>
                <body>
                  <h1>KodBank — Account Statement</h1>
                  <p class="sub">Generated by KodBank</p>
                  <div class="meta"><strong>Account:</strong> %s</div>
                  <div class="meta"><strong>Card:</strong> %s</div>
                  <div class="meta"><strong>Balance:</strong> Rs. %s</div>
                  <div class="meta"><strong>Entries:</strong> %d</div>
                  <table>
                    <thead>
                      <tr><th>Date</th><th>Type</th><th>Amount</th></tr>
                    </thead>
                    <tbody>
                      %s
                    </tbody>
                  </table>
                  <p class="footer">This is a computer-generated statement and does not require a signature.</p>
                </body>
                </html>
                """.formatted(
                esc(accountNo == null ? "—" : accountNo),
                esc(statement.maskedCardNumber()),
                esc(statement.balance().toPlainString()),
                statement.transactions().size(),
                rows);

        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.useFastMode();
            builder.withHtmlContent(html, null);
            builder.toStream(out);
            builder.run();
            return out.toByteArray();
        } catch (Exception e) {
            throw new IllegalStateException("Failed to render statement PDF", e);
        }
    }

    private String esc(String s) {
        if (s == null) {
            return "";
        }
        return s.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }
}
